modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "sporenexus"
version = "${version}"
displayName = "Spore Nexus"
authors = "Okamiz"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
iconFile = "icon.png"

[[dependencies.sporenexus]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sporenexus]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sporenexus]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sporenexus.mixins.json"
